import { User } from "src/types/user";

const initialUsers: Omit<User, "id">[] = [
  {
    name: "John",
    surname: "Doe",
    email: "john.doe@usersdot.com",
    password: "password",
    age: 30,
    country: "USA",
    district: "NY",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Jane",
    surname: "Doe",
    email: "jane.doe@usersdot.com",
    password: "password",
    age: 25,
    country: "USA",
    district: "CA",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Alice",
    surname: "Smith",
    email: "alice.smith@usersdot.com",
    password: "password",
    age: 28,
    country: "Canada",
    district: "Toronto",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Bob",
    surname: "Johnson",
    email: "bob.johnson@usersdot.com",
    password: "password",
    age: 35,
    country: "USA",
    district: "TX",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Charlie",
    surname: "Brown",
    email: "charlie.brown@usersdot.com",
    password: "password",
    age: 40,
    country: "UK",
    district: "London",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "David",
    surname: "Williams",
    email: "david.williams@usersdot.com",
    password: "password",
    age: 33,
    country: "Australia",
    district: "Sydney",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Emily",
    surname: "Taylor",
    email: "emily.taylor@usersdot.com",
    password: "password",
    age: 29,
    country: "Canada",
    district: "Vancouver",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Frank",
    surname: "Miller",
    email: "frank.miller@usersdot.com",
    password: "password",
    age: 45,
    country: "Germany",
    district: "Berlin",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Grace",
    surname: "Wilson",
    email: "grace.wilson@usersdot.com",
    password: "password",
    age: 22,
    country: "UK",
    district: "Manchester",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Henry",
    surname: "Davis",
    email: "henry.davis@usersdot.com",
    password: "password",
    age: 31,
    country: "USA",
    district: "FL",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Ivy",
    surname: "Moore",
    email: "ivy.moore@usersdot.com",
    password: "password",
    age: 26,
    country: "USA",
    district: "IL",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Jack",
    surname: "Taylor",
    email: "jack.taylor@usersdot.com",
    password: "password",
    age: 32,
    country: "USA",
    district: "CA",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Karen",
    surname: "Anderson",
    email: "karen.anderson@usersdot.com",
    password: "password",
    age: 39,
    country: "Australia",
    district: "Melbourne",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Leo",
    surname: "Martinez",
    email: "leo.martinez@usersdot.com",
    password: "password",
    age: 27,
    country: "Spain",
    district: "Madrid",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Mia",
    surname: "Rodriguez",
    email: "mia.rodriguez@usersdot.com",
    password: "password",
    age: 24,
    country: "Mexico",
    district: "Mexico City",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Nathan",
    surname: "Garcia",
    email: "nathan.garcia@usersdot.com",
    password: "password",
    age: 36,
    country: "USA",
    district: "NV",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Olivia",
    surname: "Hernandez",
    email: "olivia.hernandez@usersdot.com",
    password: "password",
    age: 23,
    country: "USA",
    district: "TX",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Paul",
    surname: "Lopez",
    email: "paul.lopez@usersdot.com",
    password: "password",
    age: 34,
    country: "USA",
    district: "AZ",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Quinn",
    surname: "Martin",
    email: "quinn.martin@usersdot.com",
    password: "password",
    age: 29,
    country: "Canada",
    district: "Montreal",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Rachel",
    surname: "White",
    email: "rachel.white@usersdot.com",
    password: "password",
    age: 21,
    country: "USA",
    district: "NY",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Samuel",
    surname: "Thomas",
    email: "samuel.thomas@usersdot.com",
    password: "password",
    age: 38,
    country: "USA",
    district: "WA",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Tina",
    surname: "Clark",
    email: "tina.clark@usersdot.com",
    password: "password",
    age: 27,
    country: "USA",
    district: "MA",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Umar",
    surname: "Ali",
    email: "umar.ali@usersdot.com",
    password: "password",
    age: 33,
    country: "Pakistan",
    district: "Karachi",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Victoria",
    surname: "Nguyen",
    email: "victoria.nguyen@usersdot.com",
    password: "password",
    age: 29,
    country: "Vietnam",
    district: "Hanoi",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Will",
    surname: "Cooper",
    email: "will.cooper@usersdot.com",
    password: "password",
    age: 35,
    country: "Australia",
    district: "Brisbane",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Xander",
    surname: "Hughes",
    email: "xander.hughes@usersdot.com",
    password: "password",
    age: 31,
    country: "UK",
    district: "Liverpool",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Yasmin",
    surname: "Singh",
    email: "yasmin.singh@usersdot.com",
    password: "password",
    age: 28,
    country: "India",
    district: "Mumbai",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Zara",
    surname: "OConnor",
    email: "zara.oconnor@usersdot.com",
    password: "password",
    age: 24,
    country: "Ireland",
    district: "Dublin",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Alex",
    surname: "Patel",
    email: "alex.patel@usersdot.com",
    password: "password",
    age: 30,
    country: "India",
    district: "Delhi",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Bella",
    surname: "Carter",
    email: "bella.carter@usersdot.com",
    password: "password",
    age: 26,
    country: "Canada",
    district: "Ottawa",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Chris",
    surname: "Moreno",
    email: "chris.moreno@usersdot.com",
    password: "password",
    age: 33,
    country: "USA",
    district: "NV",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Diana",
    surname: "Torres",
    email: "diana.torres@usersdot.com",
    password: "password",
    age: 29,
    country: "Mexico",
    district: "Guadalajara",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Eric",
    surname: "Chen",
    email: "eric.chen@usersdot.com",
    password: "password",
    age: 32,
    country: "Taiwan",
    district: "Taipei",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Fiona",
    surname: "Park",
    email: "fiona.park@usersdot.com",
    password: "password",
    age: 27,
    country: "South Korea",
    district: "Seoul",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "George",
    surname: "Wright",
    email: "george.wright@usersdot.com",
    password: "password",
    age: 37,
    country: "USA",
    district: "CA",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Hana",
    surname: "Yamamoto",
    email: "hana.yamamoto@usersdot.com",
    password: "password",
    age: 25,
    country: "Japan",
    district: "Tokyo",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Ivan",
    surname: "Petrov",
    email: "ivan.petrov@usersdot.com",
    password: "password",
    age: 40,
    country: "Russia",
    district: "Moscow",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Julia",
    surname: "Kowalski",
    email: "julia.kowalski@usersdot.com",
    password: "password",
    age: 23,
    country: "Poland",
    district: "Warsaw",
    role: "user",
    createdAt: "",
    updatedAt: ""
  },
  {
    name: "Kendrick",
    surname: "Diaz",
    email: "kendrick.diaz@usersdot.com",
    password: "password",
    age: 34,
    country: "USA",
    district: "LA",
    role: "user",
    createdAt: "",
    updatedAt: ""
  }
];

export default initialUsers;
