name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Set up Node.js for frontend
        uses: actions/setup-node@v3
        with:
          node-version: 21
          cache: "yarn"
          cache-dependency-path: ./client/yarn.lock

      # ESLint and Prettier must be in `package.json`

      - name: Install Node.js dependencies for frontend
        run: yarn install
        working-directory: ./client

      - name: Run linters for frontend
        run: yarn lint
        working-directory: ./client

      - name: Fix prettier issues for frontend
        run: yarn prettier:write
        working-directory: ./client

      - name: Set up Node.js for backend
        uses: actions/setup-node@v3
        with:
          node-version: 21
          cache: "yarn"
          cache-dependency-path: ./backend/yarn.lock

      - name: Install Node.js dependencies for backend
        run: yarn install
        working-directory: ./backend

      - name: Run linters for backend
        run: yarn lint
        working-directory: ./backend

      - name: Fix prettier issues for backend
        run: yarn prettier:write
        working-directory: ./backend

        # Fail the workflow if the linters fail
        continue-on-error: false
